Unitech/pm2

lib/God.js
lib/God/ActionMethods.js
lib/Worker.js

This fixes an issue where 2 simultaneous `restart`'s on a `fork_mode` process results in 2 running processes.

Never start a process that already has a PID

---

bin/pm2
constants.js
lib/CLI.js
lib/scripts/io.keymetrics.PM2.plist
lib/scripts/pm2-init-amazon.sh

Base on [launchd(8)](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/launchd.8.html)
Tested on 
- OS X 10.8.5
- OS X 10.9.4
Need more tests.

Darwin startup script

---

ADVANCED_README.md

Update ADVANCED_README.md to reflect apparent changes for ignore-watch param in JSON app declaration.
--------------
Hi all, sorry if I'm incorrect about this—I don't have time to dig into your code right now—but it seems that this param has changed at some point.  If I'm right, now you have a handy PR you can merge for a doc update, if I'm wrong… oh well a find & replace op wasted is all.

`ignoreWatch` => `ignore_watch` in advanced readme

---

lib/CLI.js

Fixing spelling mistake in cli message developped -> developed

Fixing spelling mistake in cli message developped -> developed

---

lib/CLI.js

In #993 I described what happens if you leave out the argument for `--instances`
I've added a simple fix to check if conf.instances is NaN to avoid this

Fixed improper '--instances' parsing

---

lib/scripts/io.keymetrics.PM2.plist

Hi,
I've been trying darwin startup script on Yosemite, and in error log it always gave me this message:
env: node: No such file or directory
Can't say why as nothing seems to be missing in plist file. I also tried to create the launch plist by myself and results where similar. 
Anyway by running the command with bash, everything works fine. I couldn't test it in older OS though.

darwin startup script fix on yosemite

---

lib/CLI.js
test/bash/env-refresh.sh
test/fixtures/env-refreshed.json

This allows the env option to handle simple values and objects, like:
```json
"env": {
"LIMIT": 10,
"CONFIG": {
"enabled": true
}
}
```
Which will be passed on as `LIMIT='10'` & `CONFIG='{"enabled":true}'`.

stringify env values to handle non-string variables from json file

---

examples/process.json

watch parameter per documentation is a boolean.  Source code shows it to be as well.  The value was improperly set to a string value "truee"
instances parameter per deprecation warnings explains to use 0 instead of max.

Update one incorrect type and one deprecated value

---

lib/scripts/pm2
lib/scripts/pm2-init-amazon.sh
lib/scripts/pm2-init-centos.sh
lib/scripts/pm2-init.sh

Fix System Path being used before NODE_PATH, to override system installed versions of node(/iojs). #1121

Use NODE_PATH before system paths

---

ADVANCED_README.md

pid is documented as an int in the programatic api - it should be string.

Correct documentation for pid option in Start programmatic API

---

lib/scripts/pm2-init.sh

Hey,
In a recent attempt to use PM2 on an Ubuntu instance (on an AWS EC2 instance), using the startup script failed for me. After some probing around i identified the problem was that when using pm2 with a system user for startup, i.e invoking:
```
$ pm2 startup ubuntu -u www-data
```
The resulting init script would fail to execute correctly due to www-data having no login by default (by default on Ubuntu its shell is set to /usr/sbin/nologin). 
changing the super() command to invoke su with -s /bin/bash seems to work and I cannot see any scenario where this would be a problem in this context.
Attached the PR for this issue, happy to iterate on this with you guys
thanks,
Adam

use bash shell by default in pm2 ubuntu init script

---

lib/scripts/pm2
lib/scripts/pm2-init-amazon.sh
lib/scripts/pm2-init-centos.sh
lib/scripts/pm2-init.sh

This is a quick fix to update the majority of the init scripts to set the PM2_HOME environmental variable to whatever it's defined on the session of the user running pm2.
Not having this caused $PM2_HOME to default to $HOME/.pm2 which might not be consistent and break the startup ability - since dump was created in a different location.
It also ports the run as user ability from the centos init script to the amazon init script.

Set PM2_HOME on the user session starting pm2.

---

lib/CLI.js

Fix for https://github.com/Unitech/PM2/issues/1460
When running "startup" command, the entire .pm2 folder or some content may be created in user's home with root ownership. Fixed by executing pm2 through su.

Fix for startup creating .pm2 folder owned by root in user folder

---

lib/Common.js

Should behave the same as cli (cli should probably use common.prepareConf instead of verifying the conf manually).

Change default exec mode to fork in prepareConf

---

bin/pm2
lib/Watcher.js

- Don't exit es6 tests if nodejs is detected
- Fix #1578 by using pm_cwd instead of env.PWD

Fix #1578 + test ES6 with nodejs 

---

lib/CLI.js

Sometimes the callback that is passed to pm2.deploy is never called. This means tools that use PM2 cannot know when it has completed deploying the code. This commit makes sure we call the callback before exiting.
Fix #1671

Be sure to call the callback passed to `pm2.deploy`

---

ADVANCED_README.md
README.md

There was a mistake in the url for the contributors in both the readme files, this commit fixes that.

Fix broken link for contributors page

---

lib/God/Methods.js

Fix process not recycled properly on Windows

---

lib/scripts/pm2-init.sh

load configuration from /etc/default/pm2

---

lib/CLI/Deploy.js
test/fixtures/deploy.json
test/pm2_programmatic_tests.sh
test/programmatic/deploy.js

When the user deploys without supplying an argument for environment, if there's only 1 defined environment in the ecosystem.json, deploy to that environment.
This is a followup to #1774.

Deploy to default environment.

---

lib/scripts/pm2-freebsd.sh

Add rcorder dependency on LOGIN to make auto-start on boot work. Without this, PM2 does not start up automatically on boot on a standard FreeBSD 10.2 installation (even if pm2_enable=YES is set in rc.conf).

Fix auto-start on boot

---

lib/God/Methods.js

I just experimented and observed that the "real" time allotted for the process shutdown does not match recorded in the log.
in my app.json "kill_timeout" = 300 
```
{
"name": "app",
"script": ".",
"kill_timeout": 300
}
```
but in the log I could see conflicting information:
(each `PM2 Process with pid 10696 still not killed, retrying...` = 100 ms)
```
PM2 Stopping app:app id:0
app-0 SIGINT
PM2 Process with pid 10696 still not killed, retrying...
PM2 Process with pid 10696 still not killed, retrying...
PM2 Process with pid 10696 still alive after 1600ms, sending it SIGKILL now...
```
so, pls accept my oneline fix :)

fix logging wrong "kill_timeout" into God#processIsDead

---

lib/CLI.js

When `conf.script` is `undefined`, `p.basename` currently returns `"undefined"` in Node.js v5.x. v6.0.0 throws an exception in this case. I'm not sure what it is expected to be so I reproduced the behavior.
Perhaps it should be the empty string instead ?

fix cli for node v6

---

bin/pm2-dev
lib/CLI.js
lib/Common.js
lib/Modularizer.js
lib/Utility.js
package.json

Hello,
I already made a PR some time ago (PR #1713) that allows to install module from .tgz packages (generated with the `npm pack` command). But there is a little issue: when updating a package with the `pm2 install foo.tgz` command, it does not updates the package and it starts a new instance of the already installed package. This PR fixes this issue.
Regards,

Allows to update packages from tarball generated with 'npm pack'

---

lib/Modularizer.js

Clean up shelljs npm install code for modules as shelljs supports a silent option
Additionally : pm2 modules are completely broken on Windows (and have been for quite some time) because of the /dev/null dependency.  This fixes https://github.com/Unitech/pm2/issues/1750

Replace shelljs "ugly hack" with shelljs support for silent console

---

lib/API.js
test/bash/pm2-dev.sh
test/fixtures/pm2-dev/app.js
test/fixtures/pm2-dev/app.json

Fix pm2-dev issue - #2366 
Do not override the application config with the opts default values.
| Fixed tickets | #2366

Do not override app config with opts default values (fix #2366)

---

package.json

I just installed PM2 on a fresh install of Windows 10. I'm using latest LTS version of node and NPM. 
When I ran `npm i -g pm2`, I had `pm2-deploy@0.3.1` installed which was causing problems when deploying to production servers (similar to this issue: https://github.com/Unitech/pm2-deploy/issues/46). I had to manually go to the `pm2` install location and run `npm i pm2-deploy@latest` to fix this issue.

chore(): update pm2-deploy version

---

lib/API.js
test/programmatic/api.mocha.js

Hi, I added this function to start up modules programatically, because using API.connect with no daemon set to true eventually results in the modules not being launched at [line 134 of API.js](https://github.com/Unitech/pm2/blob/development/lib/API.js#L136)
```javascript
if (meta.new_pm2_instance == false)
return cb(err, meta);
```
Cheers!
| Fixed tickets | none

Added launch modules function to api.

---

lib/Common.js

#2545 process started with pm2 api inherit wrong exit_code env value

---

lib/templates/init-scripts/systemd.tpl

| Fixed tickets | #2590 
See issue #2590 and this post : https://bugs.freedesktop.org/show_bug.cgi?id=73177

(startup tmpl) wrong cmd for systemd #2590

---

bin/pm2-docker

Fix for this issue: #2580
make ```pm2-docker``` use pm2_home env variable
cc @vmarchaud 
| Fixed tickets | #2580

pm2-docker pm2_home env variable

---

lib/API/Startup.js

Overwriting rc.conf on FreeBSD is very serious and will lead to a non-working system at the next reboot, as all IP address information, daemon configuration, etc. is lost.

Fix FreeBSD rc.conf overwrite

---

README.md

Add the [PM2 tutorial series](https://futurestud.io/tutorials/pm2-utility-overview-installation) as a resource within the Readme

Add PM2 tutorial series to resources

---

lib/API.js
lib/API/schema.json

| Fixed tickets | http://stackoverflow.com/questions/29923275/using-pm2-how-can-i-deploy-my-node-js-app-to-multiple-environments-and-ports-on
In `ecosystem.config.js`, the names of `apps` are given as hardcoded strings. Thus, it is impossible to start multiple instances of the same application in different environment mode. For example, if I run a particular app in production mode, and simultaneously want to start another instance of the app in the same server (but different port) in …

Allow starting processes for each environment

---

lib/templates/init-scripts/systemd.tpl

Fixed issue: because ExecStart is a `resurrect --no-daemon` all logs from all apps are streamed and are logged in the systemd journal, which is a different behavior than before a server reboot or a `service pm2 restart`. Changing the type to `forking` and removing the no-deamon flag seems to solve the problem.
(I am not a systemd expert, so I might be overlooking something)

Make sure pm2 does not fill up systemd logs

---

lib/API/Extra.js

| Fixed tickets | none
When using PM2 as API, sometimes it doesn't call the callback passed to trigger() function. I've found that it happens when msgProcess()'s callback is called before the bus event is received (process_wait_count still be a zero). So, we wait for bus launch, register listener on it, and then send a message to process.

Fix trigger API never calling callback

---

lib/API/Log.js

The timestamp when logging in JSON uses two (not influenceable) different formats when using pm2-docker.
This change makes sure all logs in JSON use the same formatting for timestamps. (ISO8601)

Make JSON log stream timestamp consistent

---

lib/API/Modules/Modularizer.js
lib/Utility.js

Fixed the broken installation of modules specified as Github repository with non-master branch. Fixed the broken upgrade of modules specified by Github source (old version was not been removed, therefore two instances existed in memory after upgrade).
Fixes issue #2809 .
| Fixed tickets | #2809

Fix #2809 - Install PM2 module from Github's non-master branch

---

lib/API/LogManagement.js

Fixed #2868 : now will display previous logs for raw option.

(bugfix) #2868: fix --raw not display previous logs

---

README.md

After 2.2 to 2.4 upgrade `restart` doesn't remember the named env it was deployed to
| Bug fix?      |no
| Documentation | yes

Update restart command usage

---

lib/ProcessContainer.js

The overrides for `process.stdout.write` and `process.stderr.write` did not invoke the provided callbacks when they’re done.
This solution is a bit hacky because it just waits for `stds.out` and `stds.err`, respectively. A proper fix should wait for all of the downstream writes (`std.std` and/or `std.out/err` and/or `process.send`, depending on the configuration), before invoking the callback – and forward any potential errors.
| Tests pass?   | no, but the same four tests also fail on `development`
| Fixed tickets | -
| Doc PR        | -

Fix: Callbacks for process.stdout / .stderr

---

constants.js
lib/HttpInterface.js

| Fixed tickets | #452
Re-submit of https://github.com/Unitech/pm2/pull/459
Let's try not to wait 3 years this time. 😉

Stripping environment variables from the HttpInterface

---

lib/API/Startup.js
lib/God/ActionMethods.js
paths.js
test/bash/dump.sh
test/bash/resurrect.sh
test/pm2_behavior_tests.sh
test/programmatic/misc_commands.js

Backs up a dump, in case of an exception during dump save.
Renames dump.pm2 to dump.pm2.bak before writing it. Falls back to dump backup on resurrection. Removes a dump if it's broken to avoid unwanted backup overwrite.
Because the only time when we want to lose saved processes is... on second thought, no, we never want to lose them :cold_sweat:
| Fixed tickets | #2971, #2827

Dump backup

---

lib/God/ForkMode.js
lib/ProcessContainer.js
lib/Utility.js
test/programmatic/logs.js

#3045 was recently fixed an issue introduced in 2.6 but a piece of it is missing. In the event you set out_file or error_file to /dev/null, it ignores log_file.
```
| Fixed tickets | #3045
```

Do not ignore log_file when out(err)_file are NULL

---

package.json
types/index.d.ts
types/tsconfig.json

I've created a first draft of the typescript definitions file. I've attached a quick gif showing how it helps on developer workflow, even if the developer is not using Typescript (baked in in Visual Studio Code, but can easily be setup for other editors).
I've relied on the http://pm2.keymetrics.io/docs/usage/pm2-api/ documentation to create the definitions, since there's a lot of comments there I could reuse. However, this might not reflect accurately what's in code, so I'll be making a second pass at the code, making sure it accurately translates what's on the documentation. I might also add other functions that are not documented.
Let me know if this is a good direction to take this into, I hope this is helpful.
| New …

Add first draft of typescript definitions

---

constants.js

| Fixed tickets | Fixes #3036
Now the default will be either 1 or 2 depending on node version and the environment variable will still be able to overwrite the default.
I also tried the --parallel flag first, but neither in the json config nor in the cli it works with `pm2 reload`

Fix applying env PM2_CONCURRENT_ACTIONS correctly

---

lib/Utility.js
test/interface/utility.mocha.js

Use Node native url parser for `pm2 install http://modules` to eliminate query values.

fix pm2 install http://modules

---

.gitignore
lib/API/Containerizer.js
lib/binaries/Runtime4Docker.js
test/fixtures/containerizer/Dockerfile.dev
test/fixtures/containerizer/Dockerfile.prod
test/programmatic/containerizer.mocha.js

Because we want auto exit to be on by default for pm2-docker, the flag needs to be changed to explicitly turn it off. See the example at https://tj.github.io/commander.js/#Command.prototype.option for a "simple boolean defaulting to true".
The suggested fix was:
```js
if (commander.autoExit !== false) {
autoExit();
}
```
But I couldn't find a way to actually pass "false" as a value from the CLI.
If you would like to add a test for this change, l could use some help on that.
| BC breaks?    | no (print a warning message if --auto-exit is provided though)
| Fixed tickets | #3206  …

Add flag to turn off auto exit with pm2-docker

---

lib/ProcessContainerFork.js

From node v8.8.1 we received unstable es6 modules support with flag --experimental-modules.
(more about it here: https://nodejs.org/api/esm.html)
Es6 modules has broken code which depends on commonJS module system. This pull request allows initially with some hacks support es6 modules.
Note: this provides full backward compatibility with CommonJS projects.
Note: I'd hope this will be included in next pm2 release - while es6 modules are still experimental feature they are worse supporting …

- Initial es6 modules support

---

lib/God/ClusterMode.js
lib/God/ForkMode.js

| Fixed tickets | #2182 2 years old issue :D 
Just changed God spawn methods (cluster.fork options are given to spawn in nodejs code).
Thanks @milichev about the feature update in nodejs!
NB: we may want to add this option to our detached spawns:
```
M       lib/API/Startup.js
M       lib/Client.js
M       lib/Daemon.js
M       lib/Interactor/InteractorDaemonizer.js
M       lib/Satan.js
```
let me know if needed.

Implement windowsHide in God spawn methods

---

lib/API/Startup.js
lib/templates/init-scripts/rcd.tpl

| Fixed tickets | #3287
**Startup.js**
```
function detectInitSystem() {
var hash_map = {
'systemctl'  : 'systemd',
'update-rc.d': 'upstart',
'chkconfig'  : 'systemv',
'rc-update'  : 'openrc',
'launchctl'  : 'launchd',
'sysrc'      : 'rcd'
};
```
we can use [sysrc](https://www.freebsd.org/cgi/man.cgi?query=sysrc) to detect FreeBSD > 9.2
`service_name = (opts.serviceName || 'pm2_' + user);`
[rcvar]( https://www.freebsd.org/cgi/man.cgi?query=rc.d) may not contain a -
`destination = '/usr/local/etc/rc.d/' + service_name;`
port [scripts](https://www.freebsd.org/doc/en/articles/rc-scripting/article.html) should go to …

FreeBSD Startup Support

---

types/index.d.ts

See https://github.com/Unitech/pm2/blob/master/lib/API.js#L1654
The describe() function returns an array, not an object. The return typehint 
should be ErrProcDescsCallback, not ErrProcDescCallback, to reflect
the correct return type.
| Fixed tickets | None

Change type definitions to reflect correct return type of describe()

---

lib/API/Log.js

in docker/kubernetes setup, error logging depends on errors being on stderr. My app does this by default but when PM2 takes over, all logs gets combined into stdout. Which makes it really hard to automatically detect the errors. 

raw output should keep the original output stream.

---

.drone.yml
packager/build-deb-rpm.sh
packager/debian/control
packager/debian/postinst
packager/debian/postrm
packager/debian/prerm
packager/rhel/postinst
packager/rhel/postrm
packager/rhel/prerm
packager/setup.deb.sh
packager/setup.rpm.sh

add systemd configuration.
set pm2's home to /etc/pm2.
create user/group on installation - clean after remove
add automatic setup script for debian-like and rhel-like distro.
To install on debian-like systems using a one-liner:
`curl -sL https://raw.githubusercontent.com/Rohja/pm2/drone_build/packager/setup.deb.sh | sudo -E bash -`
To install on rhel-like systems using a one-liner:
`curl -sL https://raw.githubusercontent.com/Rohja/pm2/drone_build/packager/setup.rpm.sh | sudo -E bash -`
@Unitech

improve building of rpm and deb packages.

---

lib/API/Log.js

if use pm2-docker and pass --raw ,all logs gets combined into stdout.
| Fixed tickets | #3316 

raw output should keep the original output stream in docker.

---

types/index.d.ts

Add missing `env` to the TypeScript definition.

Add env to StartOptions

---

.drone.yml
packager/build-deb-rpm.sh
packager/publish_deb_rpm.sh

What this PR fix (according to private issues):
- APK Build was set to a fix version because of the `PM2_TARGET_VERSION` environment variable (used for dev/debug) being present in Drone configuration.
- RPM/DEB files don't use "build number" as part or their versions.
- DEB file is also uploaded for Ubuntu's older LTS version still active (ubuntu/trusty - 14.04)

Fix build number deb rpm

---

lib/God.js
lib/God/ForkMode.js
lib/TreeKill.js

| Fixed tickets | #2182
Works with node v9.4.0 and above.

#2182 Get rid of annoying popups in Windows 10

---

bin/pm2
lib/API/schema.json
lib/ProcessContainer.js

Add v8 option into commander to enable data collection from v8.

feat: allow pm2 to enable v8 data collecting from pmx

---

types/index.d.ts

Add sendDataToProcessId into typescript definitions

---

types/index.d.ts

Unless I'm missing something, this argument should accept an array of paths like the JSON configuration files.

Adding string[] to "watch" value in StartOptions (TypeScript definition file)

---

lib/API/schema.json
lib/God/ClusterMode.js
lib/God/ForkMode.js

Add windowsHide option to allow Windows popup from pm2 process file

---

lib/API/Version.js
lib/Client.js

Allow pull, forward and backward command to accept id/pid arg.
| Fixed tickets | #3463

feature: make "pull", "backward" and "forward" works with id and pid

---

lib/API/Startup.js
lib/God/ActionMethods.js
package.json

copyFileSync is only available for node 8.5.
Use polyfill module to be compatible with node 4.x

fix: use polyfill module for copySync with node 4.x

---

ADVANCED_README.md
constants.js
lib/API/Modules/Modularizer.js
lib/Common.js

Set ecosystem.config.js as the default ecosystem file

Set ecosystem.config.js as the default ecosystem file

---

bin/pm2

`pm2 start` with no arguments now tries to start the ecosystem file in PWD.

Start the ecosystem file in PWD by default

---

lib/API/Log.js

Signed-off-by: Nikita Nagorny <nikiton-n@mail.ru>
The PR fixes issue described here: https://github.com/Unitech/pm2/issues/3530

logs: Make padding mechanism working only if padding is longer than string

---

bin/pm2

Set the first argument of pm2 start an option rather than a required argument.
The merge of the two last week PRs have overwritten that change.

Start local ecosystem file by default

---

types/index.d.ts

Fix properties name in definition's file.
| Fixed tickets | #3605

fix: #3605 fix parameters definition, don't use camelcase for properties

---

lib/templates/init-scripts/upstart.tpl

This pull request improves `upstart.tpl` shell script syntax including:    
```
- Use spaces instead of tab for indent
- Replace deprecated `command` with $(command)
- Add missing quote to variable reference
- Separate variable declaration and assign to avoid masking return values
```
This is my first pull request to `pm2`, please let me know if there is anything I missed that should be fixed, many thanks!

Improve upstart.tpl shell script syntax

---

lib/Common.js

| Tests pass?   | N/A
| Fixed tickets | #3739
These are the minimum required changes to support `nvm` for Windows.

Add support for nvm for Windows

---

bin/pm2
lib/API/Interaction.js

https://github.com/Unitech/pm2/issues/3750
```
$ pm2 plus <sec> <pub> 
```

Generate combination of hostname and uid on link

---

package.json

revert https://github.com/Unitech/pm2/pull/3826 to keep the bug fix for node < 4.5
note that the buggy pidusage version has been unpublished and I'm very sorry it got published without me wanting to, it caused a 3h gap where pm2 installations may have break.

Pidusage@^2.0.14

---

lib/God.js
lib/God/ActionMethods.js

After my process has started and worked for a while, it can start reloading (e.g. because of data base connecting error) and the system will not stop it after n reloadings noted in settings. These changes fix this problem.

Add new feature  with unstable restart

---

lib/API/pm2-plus/process-selector.js

Use register() method to avoid exception.
| Fixed tickets | #3831

fix: #3831 switch registerToKM() to register()

---

lib/God/ActionMethods.js

If action doesn't exist we should display an error, even if we trigger action by application's name.
| Fixed tickets | #3786

fix: #3786 fix issue when triggering an action that does not exist

---

types/index.d.ts

fix: #3883 fix typings for max_memory_restart and add wait_ready

---

lib/API/Startup.js

Be sure to display backup file's path in warning message.
| Fixed tickets | #3896

fix: #3896 update file path if we are reading the backup file

---

lib/Common.js

Remove unused message about clustering.
| Fixed tickets | #3910

fix: remove warn message about clustering for old node 0.10 version

---

lib/API/Modules/NPM.js

Can't install modules on Windows when pm2 has spaces in path, i.e. "Program Files".

 Handle path spaces on Windows

---

lib/API.js

fix: limit concurrent_actions to 1 if nb process <= 2

---

lib/Common.js

This overwrites args when restarting
| Fixed tickets | #4029

Ensure node_args are not removed on restart

---

bin/pm2

pm2 should ignore -s --silent -v if they are after '--' (variadic args for start and restart commands)
Example:
pm2 start node-red --node-args="--max-old-space-size=128" -- -v
Currently just prints versions and exits.

pm2 should ignore -s, --silent, -v after '--'

---

lib/templates/init-scripts/systemd-online.tpl
lib/templates/init-scripts/systemd.tpl
packager/build-deb-rpm.sh
packager/debian/control

updates the systemd template files to auto-restart the god daemon should it somehow crash.
you can test with `sudo kill -9 <pid of god daemon>`
pm2 doesn't restart itself! even after `pm2 startup`.
this fixes that.
(also, I accidentally included a commit where I reduced the .deb packages node dep from 6.12.3 down to 6.3.0 -- that's not required for this MR, but it does help me as I've got a lot of servers w/ 6.3.0 installed...)

Auto restart god

---

lib/God/ActionMethods.js

Scoped actions require a uuid field to work, so we should make sure to send it to the child process. Currently, we only send the action name if `opts` are not defined.

fix: trigger scoped actions

---

lib/API/Startup.js

The `process.env.PATH`  is not set in the PATH of plist. And the pm2 will throw command ENOENT error because of it.
| Fixed tickets | #3879

fix spawn ps ENOENT

---

bin/pm2

| Fixed tickets | NA
- `describe` command operates with process `name` or `id`.
- `env` command is not a alias of `describe` command

Fix help message of describe/env command

---

lib/API/Startup.js

| Fixed tickets | #3732 , #1349 
The `pm2 unstartup` will always failed in macos. Because the pm2.*.plist will never been deleted.
```
commands = [
'launchctl remove ' + launchd_service_name + ' || true',
'rm ' + destination
];
```
`launchctl remove` always return no-zero value, so `rm` in the next will never been executed.

fix pm2 unstartup fialed in macos

---

lib/API/CliUx.js

Table list didn't have *version* column title, that caused a shift of other column titles.
| Fixed tickets | #4021

Fix for missing column title

---

lib/templates/init-scripts/systemd.tpl

When Ubuntu's out of memory killer kills PM2 it never restarts. Adding these lines should restart it after 30 seconds.
| Fixed tickets | #4150 

Added Restart and RestartSec into the systemd script

---

lib/API/Startup.js
lib/templates/init-scripts/smf.tpl

Currently, when running the command `pm2 startup` on Oracle Solaris or illumos-based systems like SmartOS, OpenIndiana, etc. will throw up an `Init system not found` error.
This PR adds support for using the Solaris SMF system for starting PM2 which is available on Solaris 10 or above that replaces `/etc/init.d` scripts on such platform.

Support Solaris SMF as init system

---

package.json

| Fixed tickets | #4367 
There is a new vulnerability in lodash 4.17.11. (https://www.npmjs.com/advisories/1065)
This PR updates the lodash dependency

fix: update lodash version

---

lib/binaries/Runtime4Docker.js

| BC breaks?    | yes
| Fixed tickets | #4372

fix: pm2-runtime auto-exit check ignores module like logrotate

---

lib/God/Reload.js
test/programmatic/graceful.mocha.js

| Fixed tickets | #4300,#4271
Related to this issues #4300,#4271
I've created branch from 3.5.1 (latest 3.x.x) by that moment

3.5.x: Process.send('ready') does not trigger SIGINT

---

types/index.d.ts

ref: http://pm2.keymetrics.io/docs/usage/cluster-mode/#usage
Added because the type of instance option needs to include max
| Fixed tickets | n/a

add 'max' for instances option

---

lib/templates/init-scripts/systemd-online.tpl

| Fixed tickets | #3347
The below line is not necessary.
```
Wants=network-online.target
```
pm2 still launches even though it does not meet "network-online.target".

Fix --wait-ip option doesn't work

---

lib/API.js

Running `pm2 list --watch` doesn't update the status table properly.
The escape code should be `\033`, but that doesn't work in strict mode, probably because of that it was changed to `\\033` which isn't valid either.
Tests failed
```
[~] Starting test ./test/e2e/misc/nvm-node-version.sh
######## ✘ Errors in setting interpreters
```
But that doesn't seem to be related to this change.
| Fixed tickets | #3884

fix: ANSI escape codes with --watch #3884

---

constants.js
lib/God/Methods.js
test/e2e/cli/reload.sh
test/fixtures/signal-send.js
test/fixtures/signals/delayed_send.js
test/programmatic/signals.js

| Fixed tickets | #3651, #3691, #3555
---
*Problem*:
There is no official and easy way to implement the graceful shutdown on Windows.
For graceful shutdown PM2 pretty much relies on the `process.kill()` and applications being able to ignore `SIGINT` to delay shutdown, but it doesn't work on Windows.
https://pm2.keymetrics.io/docs/usage/signals-clean-restart/
There are variables you can set to alter the PM2 kill behavior: `PM2_KILL_SIGNAL` (`SIGINT` by default), `PM2_KILL_TIMEOUT` (`1600` by default), the `--treekill` parameter (`true` by default), and kill retry time.
---
There are a couple of issues with PM2's graceful …

Adding optional switch to enable graceful shutdown on Windows

---

lib/API/CliUx.js
lib/tools/passwd.js

| Fixed tickets | #4431
This pull request should solve two issues:
1. When a process is run with uid and if the user doesn't have fullname assigned, the username is being displayed incorrectly as "root" in pm2 status
2. In Ubuntu, the value for fields[4] attribute in passwd.js consists of multiple values like full name,room number, work phone, home phone and other seperated by commas. If none of them have values assigned, the fields[4] attribute will end up having value as ",,,".

fix: display correct username

---

lib/God/ActionMethods.js

| Fixed tickets | #4485 
Solves two problems:
1. Stops and deletes the cron job during the process deletion itself. Soft reload won't be called even in absence of process.
2. Doesn't restart wrong process in the case where if new process gets spun up and gets same process id assigned to it as well

fix: stop and delete cron immediately on deletion of a process

---

lib/Daemon.js

| Fixed tickets | #3793
Although I do not use version 2, still have #3793 .
I propose change the path on Windows when get error and restart pm2.

Fix an error for pm2 path on Windows.

---

types/index.d.ts

Make typescript allow `ignore_watch` option to be set on `start()`

add `ignore_watch` to StartOptions types

---

types/index.d.ts

When calling pm2.reload you can optionally pass a parameter options to customise the restart behaviour, this is not included in the types definition.
| Fixed tickets | #4614

fix: Add type for pm2.reload with optional options parameter

---

CHANGELOG.md
lib/Common.js
lib/Utility.js
package.json

Fix disabling logs

---

lib/API/Extra.js
lib/God/ActionMethods.js
lib/God/ClusterMode.js
lib/God/ForkMode.js
lib/binaries/CLI.js

feat: trigger all the process using 'all' or trigger all processes in a particular namespace

---

lib/API/LogManagement.js
lib/binaries/CLI.js

`Usage:  pm2 logs <namespace>`

feat: print logs of a particular namespace

---

lib/Common.js

| Tests pass?   | n/a
| Fixed tickets | #4652 
This pull request fixes the following problem: If you define `type: module` inside package.json, none of the extensions on config file would work (tried with mjs and js). This happens on `pm2 deploy` command.
This is merely a temporary solution; it would be nice to support module exports, but due to require being used [here](https://github.com/Unitech/pm2/blob/master/lib/Common.js#L289), we can't. I believe this happens only on `pm2 deploy` command.

Add .cjs (common JS) as a viable extension

---

lib/Worker.js

Small fix to the grammar output to the logs when applications restart. The units of time have also been added to align to what is output during restart attempts.

Small grammar fix and addition of units to output.

---

lib/API.js

Before:
```
$ pm2 start --namespace foo ecosystem.config.js
[PM2][WARN] Applications background_worker not running, starting...
[PM2] App [background_worker] launched (1 instances)
┌─────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ background_worker    │ N/A         │ 0.0.1   │ fork    │ 86094    │ 0s     │ 0    │ online    │ 0%       │ 8.5mb    │ leon     │ enabled  │ …
```

Use opts.namespace if it was passed in. Previously, it was ignored.

---

CONTRIBUTING.md

| Bug fix?      | yes (documentation bug)
| Tests pass?   | no, but they don't pass on the development branch for me either
This is just a little doc fix, following upon the rename that happened in 8a7db95aabc8437f292af0316cec81ab80ec41f5.

Fix e2e test paths in CONTRIBUTING doc

---

lib/God/ForkMode.js

Previously, when the pm2 reloadLogs command was running as a non-root
user, the process will not release and hangs. The reason for the hang
is that the forked process never closes because the object is empty
and doesn't contain the expected object. This commit checks if an
object exists first, before trying to execute methods on it.
Related to: #4781
Co-authored-by: Franck Danard <fdanard@sangoma.com>
| Fixed tickets | #4781

Prevent reloadLogs command from hanging

---

lib/API/Modules/Modularizer.js

#4593 affected backward compatibility, if someone try to install tarball module without tarball option. 
Actually, it contains bad regular expression for following use cases:
1) Module name with digits (`pm install pm2-module-name.tar.gz`)
2) Modules/TAR.js can use Modularizer module_name as module_filepath, but #4593 regular expression is not allowed to specify full path to module (`pm install full/path/to/module/pm2-module-name.tar.gz`)
3) Modules/TAR.js can accept URL (`pm install http://example.com/pm2/pm2-module-name.tar.gz`)
| BC breaks?    | yes

fix: backward compatibility fix for tarball modules

---

test/unit.sh

This commit fixes an issue with the unit test script where it
could not be run without Mocha installed globally since there was
a bug where the alias wasn't working, but if Mocha was installed
globally, it would use that instance to run the tests. However, if
Mocha is not installed globally, then it would fail because it
pointed to the local instance of Mocha using a relative path that
was in direct conflict with the relative path used to run the local
instance of pm2. The npx command fixes these issues by finding the
local instance of a npm binary regardless of what the current
directory is. …

fix: fix unit test script

---

package.json

Related vulnerability: https://github.com/advisories/GHSA-94xh-2fmc-xf5j

Update systeminformation package to 4.27.11 (CVE-2020-7752)

---

test/unit.sh

When run with npm 7.x, the unit tests fails with the error below.
To fix this, simply don't change the CWD when executing the tests
> pm2@4.5.0 test
> bash test/unit.sh && bash test/e2e.sh
> 
> [~] Starting test ./filter_env.mocha.js
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path /home/adamm/work/node/pm2/pm2/test/programmatic/package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/home/adamm/work/node/pm2/pm2/test/programmatic/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
| Fixed tickets | --- …

tests: fix tests with npm7

---

lib/API/Dashboard.js

| Fixed tickets | #4923
I have encountered this issue when the logs from Log box in monitor/dashboard are lost upon changing the selected app. Upon further research, it seems others had this problem as well for some time now. Upon testing, now the logs are preserved on changing between apps monitored, as expected.

App logs from monitor will not be deleted on selecting a different app

---

lib/API/Startup.js

| Fixed tickets | #5193
Ensures the directory `~/Library/LaunchAgents` exists before attempting to write a file to it. Fixes #5193

Ensure directory exists before writing to it

---

lib/API/Extra.js
lib/API/pm2-plus/auth-strategies/WebAuth.js

Reduce async import

---

lib/Utility.js

fix: used env variable instead of hardcode datetime format

---

lib/API/Serve.js

Fix unnecessary "ENOENT" console.error when serving a spa

---

lib/API/Modules/TAR.js

On Windows, uninstalling a tarball module fails because pm2 execs `rm -r` which is not available on Windows. This fix replaces the call to `rm` with a call to the existing `deleteFolderRecursive` utility func.
| Fixed tickets | n/a

fix: make tarball module uninstall cross-platform

---

lib/ProcessUtils.js

| Fixed tickets | #5266
I created a [CodeSandbox](https://codesandbox.io/s/gracious-mccarthy-4dnmu) with the fixed issue (the one with the problem can be found on the [original issue](https://github.com/Unitech/pm2/issues/5266) or [HERE](https://codesandbox.io/s/focused-star-5u0qb)).
In a new terminal, you can run `npm run start1` or `npm run start2`. 
Both of them should locate the `package.json` and identify `server.js` as an ESModule correctly

Fix: #5266 - Find the nearest package.json

---

types/index.d.ts

I added a couple missing properties in Typescript definitions for `pm.start`.

Add missing start options types

---

lib/Common.js
lib/Worker.js
package.json

Replaced cron with node-schedule

---

package.json

Fix High severity vulnerability in async package

---

lib/God.js

| Fixed tickets | #4965
This ensures the `increment_var` value is coerced into a Number before attempting to perform any math operations on it. Doing so solves an issue where when you pass in a `PORT` variable through the environment rather than through the ecosystem config file, it would be read as a string and incrementing it would append the number to the string rather than actually incrementing it (e.g., `3000` would result in using ports `3000` and `30001`).

Ensure increment_var value is a Number

---

lib/God.js

With `autorestart` set to true, PM2 will restart child processes if they disconnect. However, if the process crashes internally, PM2 will not attempt to restart or replace it, leaving the overall service running with one less process.
In our case, we just upgraded to node 16 and PM2 5.2.0, and are seeing node periodically throw `ERR_IPC_CLOSED` now. We're not sure about the root cause of that error yet, but regardless, we would expect PM2 to either handle that or at least restart the crashed process. Unfortunately, it's doing neither and just letting the process permanently die.
This appears to be because PM2 [marks the process as `ERRORED_STATUS`](https://github.com/TeamGuilded/pm2/blob/master/lib/God.js#L305) in its `error` event handler, and ERRORED_STATUS processes do [not even …

PM2 does not restart crashed processes

---

examples/sourcemap-auto-resolve/API.js
lib/API.js
lib/binaries/CLI.js

| Bug fix?      | Yes
This PR fixes three simple typos consisting of: `lauch` -> `launch`

fix: all cli 'launch' typos

---

lib/API/LogManagement.js

| Fixed tickets | #4553
<h3>Changes explanation</h3>
Although the pm2 docs mentioned users can pass <app_id> as an argument to `pm2 flush <...>`, the code doesn't recognize that. So we will be using this instead:
``` javascript
else if (l.pm2_env.pm_id == api || l.pm2_env.name === api) {
<...>
}
```
Next, in the flush function, the condition to flush a file is depended as below:
``` javascript
if (l.pm2_env.pm_out_log_path.lastIndexOf('/') < l.pm2_env.pm_out_log_path.lastIndexOf(api))
```
The condition is fine, however, when the name of an app has space, the flush command will never succeed. …

hotfix: replace non-working condition that blocks flush from clearing the logs

---

lib/God.js

cron_restart is not working after resurrect
| Fixed tickets | #5443

Fix: #5443 - resume cron rule when resurrect

---

CHANGELOG.md
README.md
package.json
types/index.d.ts

Add in types
```js
/**
* NameSpace for the process
* @default 'default'
* @example 'production'
* @example 'development'
* @example 'staging'
*/
namespace?: string;
```

✅ Add Namespace type

---

README.md
lib/API/Modules/TAR.js

Fixed reserved keyword for ES6 Strict Mode when Bundling

---

lib/API/Log.js
test/e2e.sh
test/e2e/logs/log-namespace.sh
test/fixtures/log-namespace/echo.js

| Fixed tickets | #5658
| Doc PR        | N/A (?)

Fix matching logic for logs from namespace when lines = 0

---

lib/API/UX/pm2-describe.js

| Fixed tickets | #5832
envs like `vizion_running` and `vizion_running` are Boolean not String. See:
https://github.com/search?q=repo%3AUnitech%2Fpm2+%22env.vizion_running%22&type=code
https://github.com/search?q=repo%3AUnitech%2Fpm2%20%22env.updateEnv%22&type=code

fix: env output in pm2-describe

---

lib/API/Modules/Modularizer.js
lib/API/Modules/TAR.js
lib/binaries/CLI.js

| Fixed tickets | #5680
1) enbale module:update tarball
2) update TAR.package to TAR.packager

fix: Enable PM2 module update from tarball

---

lib/TreeKill.js

Fixes 5895 - treekill syntax incompatible with freebsd

---

lib/Client.js
lib/Worker.js

| Fixed tickets | #4695
This adds support for a `PM2_DISABLE_VERSION_CHECKS` env variable, which will disabling running version checks for PM2.

Add support for disabling version checks

---

bun.lock
package-lock.json
package.json

| Fixed tickets | #5984
Hello @Unitech,
This PR fixes the incompatibility with Node.js <= 12 introduced with the PR #5983. I'll leave this as a draft for now.
Although PM2 v6 officially [requires at least Node.js 16](https://github.com/Unitech/pm2/blob/e71120a5172e87f509563f2542942458b115783a/package.json#L6), many users continue to run pm2 v6 on unsupported Node.js versions 10–12.
Many other dependencies require Node.js 14+:
- proxy-agent@6.4.0
- agent-base@7.1.3
- http-proxy-agent@7.0.2
- https-proxy-agent@7.0.6
- socks-proxy-agent@8.0.5
- …

fix: cannot find module ansis on Node.js < 14

---

lib/tools/Config.js
test/interface/redos.mocha.js
test/unit.sh

Steps to reproduce
Hello,
I am writing to report a potential Regular Expression Denial of Service (ReDoS) vulnerability or Inefficient Regular Expression in the project. When using specially crafted input strings in the context, it may lead to extremely high CPU usage, application freezing, or denial of service attacks.
Location of Issue:
The vulnerability is related to a regular expression used in the following validation file, which may result in significantly prolonged execution times under certain conditions. …

fix:Potential ReDoS Vulnerability or Inefficient Regular Expression in Project: Need for Assessment and Mitigation
