Unitech/pm2

ADVANCED_README.md, lib/Watcher.js, lib/schema.json, test/bash/watch.sh, test/fixtures/donotwatchme.sym, test/fixtures/server-watch.json
Add watch options to pass to chokidar. Added a few docs too.
@jshkurti I've transformed a log into `console.error` to output to stderr, tell me if you (dis)agree with it :) (see last commit)
=> Watch options fix #931 #870

.gitignore, README.md, lib/Satan.js
Easy one line fix...
Optionally ignore the IDEA project files...
=> Fix for PM2 in Windows when PM2_HOME environment var not set

lib/Monit.js
add simple if-guard to Monit.updateBars
fixes #1002
=> fix error in `pm2 monit` when `pm2 reload`ing

lib/CLI.js
=> Improve instance option parsing to avoid fork bomb, fix #1091

ADVANCED_README.md, bin/pm2, lib/CLI.js, lib/God/Methods.js, lib/Satan.js, lib/Worker.js, test/bash/misc.sh
You can now ```pm2 gc``` to manually trigger garbage collection for the PM2 daemon process.
=> new command: pm2 gc (triggers garbage collection)

README.md
Much higher quality.
vs.
(Even higher quality when not pasting screenshot into GitHub...)
https://github.com/SimenB/PM2/blob/badges/README.md
=> Use svg-badges in README

lib/CLI.js
pm2 flush CLI command did not flush pm2_env.pm_log_path
=> Flush pm_log_path

bin/pm2, lib/God/ActionMethods.js, lib/God/Methods.js, lib/schema.json
I really need this because I'm handling detached processes in my main process.
=> Add a --no-treekill option to avoid killing detached processes

lib/CLI.js, lib/Common.js
- Fixes the issue on CentOS when the output of `pm2 list` was truncated.
=> Truncated output fix

ADVANCED_README.md, bin/pm2, lib/completion.js, lib/completion.sh
commander.commands is not mapped before the **completion** check, therefore no base command is avalaible
=> Autocompletion based on tabtab 

ADVANCED_README.md
Fix broken links in advanced readme
=> Fix broken links in advanced readme

constants.js
Added HOMEDRIVE environment variable to PM2_ROOT_PATH when on Windows. Fixes #1251.
=> Fix Windows issue

examples/process.json, lib/Watcher.js, test/programmatic/json_validation.mocha.js
=> Fix some watch issues

lib/CLI.js
Fix for https://github.com/Unitech/PM2/issues/1459
=> Fix for startup systemd not working when user is not root

lib/Interactor/Filter.js
cf https://github.com/Unitech/PM2/pull/1606 https://github.com/Unitech/keymetrics.io/issues/88
=> node_version notation changed

lib/Modularizer.js
Hello,
This PR enables PM2 to install packages from tarball (generated with the `npm pack` command), if the tarball is properly named:
pm2 install myapp.tgz
pm2 install myapp-1.0.0.tgz
pm2 install http://example.com/packages/myapp-1.0.0.tgz
// PR #1705 but, on the right branch :)
=> Allows to install packages from tarball generated with 'npm pack'  #2

package.json
Replace the `true` String with a `true` Boolean... I think NPM is strict on this value?
Not that PM2 has a problem being found. :smile:
=> Update the package.json preferGlobal key

lib/Common.js, lib/Watcher.js, test/programmatic/programmatic.js
Hi guys!
This is only a proposition of a fix for #1764, because first Automattic/cli-table#83 should be accepted and updated. Once they release fixed version, I'll rebase PR with `package.json` update also. And then, all tests will pass, and we'll be good to go. :wink: 
/cc @Unitech @soyuka
=> Fix Watcher to be able to run application with whatever name

package.json
Update yaml.js to v0.2.8. Fix ReDos, see https://snyk.io/test/github/Unitech/pm2
| Tests pass?   | no - please restart the build
| Doc PR        | https://snyk.io/test/github/Unitech/pm2
=> Update yaml.js - fix ReDoS

bin/pm2, constants.js, lib/HttpInterface.js
| Test Pass? | yes
| Fixed tickets | #2294
=> Allows to specify an IP Address for the WEB API to bind on

lib/API.js, lib/API/Extra.js
| Fixed tickets | #1357
| License       | GNU-AGPL-3.0
=> fallback to process.cwd for windows

lib/API/Startup.js
=> fix #1063 change startup script destination (for Gentoo/OpenRC)

lib/API/LogManagement.js
=> bugfix: variable "that" is not defined

bin/pm2
=> (cli)(completion) #2381 fix completion install hang

lib/ProcessContainer.js
=> fix handle null rejection

package.json
=> update pidusage, fix windows 10 issues with wmic

lib/templates/logrotate.d/pm2
| Fixed tickets | #2498
| Doc PR        | na
=> Logrotate on all files in ~/.pm2/logs

lib/Interactor/PushInteractor.js
=> (feature) attach last 25 logs when sending exception to km

README.md
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |
| Doc PR | N/A |
=> Fixed spelling on `# Reset all counbters`

lib/API/Startup.js, lib/templates/init-scripts/openrc.tpl
=> Support openrc (gentoo linux).

lib/API/Startup.js
=> fix #2617 only load startup file with launchctl

README.md
Provide workaround for https://github.com/Unitech/pm2/issues/1627
| Bug fix?      | workaround
| Fixed tickets | #1627 
=> Update README to prefer `pm2 restart json_conf`

lib/API/Startup.js
Discussion: https://github.com/Unitech/pm2/commit/a788e523e5843a9053f455072ab79cceac460181#commitcomment-20851443
| BC breaks?    | no (afaik)
| Fixed tickets | -
| Doc PR        | -
=> (startup) fix systemv on debian

lib/God.js, lib/God/ActionMethods.js
| Fixed tickets | #1966, #1939
Add a timeout-handle to stop the auto restart.
=> fix the bug: "process still restart after it has be stop or delete"

lib/Common.js
When set `cwd` environment variable, checking log folder seems not to be right.
Before:
=> fix log folder create

lib/Client.js
| Tests pass?   | passing locally
| Fixed tickets | #2651
I have also tested that it this commit is able to start the daemon from an electron process 🙌
=> Always start the deamon using node

lib/API.js
Fix for Processes file doesn't accept Window absolute paths #2796
| Fixed tickets | #2796 
=> Fixed absolute paths in process files #2796

lib/API.js
=> Fix #2815 nodejs 0.11 compatibility is Absolute

lib/Common.js
=> (update) #2872: no load balance warn for 1 instance config

lib/API/Deploy.js
I can't figure out what dies happens. So go to serf sources of `pm2`... Think my small addition will be useful.
=> "Not any default deployment file exists" error explanation

lib/God.js
=> add wait ready for cluster mode

lib/API/LogManagement.js
Have updated the code to accept regex for 'pm2 logs' just like start.
| Fixed tickets | #2888 
=> Update pm2 logs to accept regex for names

lib/API.js, package.json
The older version of async is causing issues with CLS in my application.
=> updates async version

lib/Interactor/Daemon.js, lib/Interactor/InteractorDaemonizer.js
Updating the email addresses that are used to contact support when some error messages occurs
=> Support email address edit 

lib/Interactor/Daemon.js, lib/Interactor/InteractorDaemonizer.js
=> Revert "Support email address edit "

.gitattributes
=> Fix shell scripts EOL on Windows

package.json
=> force upgrade to latest pm2-deploy, fixes #3181

lib/API/interpreter.json, lib/ProcessContainer.js
| Fixed tickets | #3199
| Doc PR        | None
=> Associate .tsx files with ts-node

lib/Utility.js, test/interface/utility.mocha.js
For example `pm2 install file:///home/user/module`
=> Allow installing modules from local file destinations

lib/binaries/Runtime4Docker.js
=> Fix docker-pm2 to accept official PM2 home env var

README.md
=> Changed OS X to macOS as Apple changed the OS name

lib/Common.js
=> Fix an error message typo

lib/API/Extra.js, test/programmatic/send_data_process.mocha.js
=> Fix the send_data_process bug

CONTRIBUTING.md
Saw something missing from the project structure, so decided to contribute. Let me know if there's anything I need to do etc!
=> Adding in types into project structure

lib/God/ActionMethods.js
=> Wrong typeof comparison on undefined

lib/ProcessContainerFork.js
=> Fix gid when both --uid and --gid specified

README.md, bin/pm2, lib/API.js, lib/API/CliUx.js, test/bash/sort.sh, test/fixtures/sort/http.js, test/fixtures/sort/other.js
Add sorting feature.
| Fixed tickets | #3296
=> add sorting feature for process list

package.json, test/bash/interpreter.sh, test/pm2_check_dependencies.sh
Check dependencies (php, node, nvm, python) before launch test.
=> Test dependencies

lib/API.js, lib/API/CliUx.js, lib/Common.js, lib/God.js
PM2 display user according to os.userInfo().username just before printing results.
At this moment the user is the one who launched PM2 Cli and not the one who started the application.
Move the code into executeApp function in God.js solves the problem.
| Fixed tickets | #3360
=> #3360 pm2 show wrong user, now display user who started the application

lib/API/Modules/Modularizer.js
Allows PM2 to install gc-stats
| Fixed tickets | #3380
=> Install Gc stats

lib/API/schema.json, lib/ProcessContainer.js, lib/ProcessContainerFork.js
Fix, replace dash with underscore for commander arguments.
=> fix: replace dash with underscore

bin/pm2, lib/API/schema.json, lib/ProcessContainer.js, lib/ProcessContainerFork.js
Add flog to CLI/JSON to enable deep-monitoring.
=> feat: add flag to enable deep-monitoring

lib/Common.js
Add .mjs support
| Fixed tickets | #3479, #3478
=> feature: add mjs support

bin/pm2, lib/API/Startup.js, lib/God/ActionMethods.js, test/programmatic/programmatic.js
Try to fix issue with empty dump file.
+ add cleardump command to force a new empty dump file.
| Fixed tickets | #3485
=> Dump refacto

bin/pm2, lib/Daemon.js, lib/God/Methods.js, lib/Satan.js
Fix issue with snapshot command and clean unused code.
| Fixed tickets | #3505, #2392
=> chore: fix issue with snapshot command + remove command forceGc

bin/pm2, lib/API/Extra.js, lib/API/Startup.js, lib/API/schema.json, lib/Daemon.js, lib/God/ActionMethods.js, lib/God/Methods.js, lib/ProcessContainer.js, lib/ProcessContainerFork.js, lib/ProcessUtils.js, lib/Satan.js, test/programmatic/programmatic.js
add inspector feature on process container.
Use pmx, not need to reload/restart app.
=> feature: add inspect feature, on runtime

lib/API/Log.js
=> Revert "logs: Make padding mechanism working only if padding is longer than string"

lib/God.js, lib/God/ActionMethods.js, package.json, test/programmatic/god.mocha.js
=> Improve monitoring performances

lib/ProcessUtils.js, test/interface/bus.fork.spec.mocha.js, test/interface/pm2.link.check.mocha.js
=> fix: remove unused variable when trying to use tracing

lib/API/Log.js
Signed-off-by: Nikita Nagorny <nikiton-n@mail.ru>
The PR fixes issue described here: https://github.com/Unitech/pm2/issues/3530
=> logs: Make padding mechanism working only if padding is longer than string

lib/binaries/Runtime4Docker.js
=> fix: reinforce pm2-runtime auto exit strategy #3567 #3206

lib/God/ActionMethods.js
| Fixed tickets | #3571 
full description see #3571 ,something wrong on last PR #3572  so I create a new.
=> Fix the bug: process with "restart-delay" can't restart when manually stop

CONTRIBUTING.md
=> Add changelog generation into contributing.md

lib/API/Extra.js
Change method to compare version to make it work with alpha/beta tags.
| Fixed tickets | #3695
=> fix: #3695

lib/API/CliUx.js
=> Fix cpu value for modules

lib/God/ActionMethods.js
| Fixed tickets | https://github.com/Unitech/pm2/issues/3735
=> fixes #3735

lib/API/CliUx.js
=> add node env when using show command

packager/debian/postinst, packager/debian/prerm, packager/rhel/postinst, packager/rhel/prerm, packager/setup.deb.sh, packager/setup.rpm.sh
This pull requests fix the inconsistency in shell script indentation, the inconsistency also breaks current rule in `.editorconfig`.
=> fix: retab shell script to use space for indent consistency

lib/API.js
=> fix: option -w doesn't work

CHANGELOG.md, bin/pm2, lib/API/Containerizer.js, lib/API/Monit.js, lib/Common.js, lib/tools/xdg-open, test/e2e/logs/log-entire.sh, test/e2e/modules/get-set.sh
=> Fixed grammar: 'does not exists' -> 'does not exist'

lib/Daemon.js
Add inspector for node 10 and heap snapshot.
=> feature: add inspector for node 10 and heap snapshot

package.json
Because of https://github.com/soyuka/pidusage/issues/73
| BC breaks?    | 
| Tests pass?   | 
| Fixed tickets | #3825
=> Pin pidusage to v2.0.13

lib/API.js
=> Variable gl_retry

lib/API/Startup.js
=> fixed unstartup when launchd

package.json
Upgrade vizion to 2.0.0.
| Fixed tickets | #3415
=> chore: #3415 try to update vizion to 2.0.0

bin/pm2, lib/API/LogManagement.js, test/programmatic/flush.mocha.js
| Bug fix?      |no
| Fixed tickets | #3412
=> added parameter to flush command(added tests)

lib/API/CliUx.js
=> feature: add id column in stacked mode (80 char mode)

lib/API/LogManagement.js
=> fix for issue #3506

lib/ProcessContainer.js, lib/ProcessContainerFork.js, lib/Worker.js, test/fixtures/cron_no_autorestart.js
| Fixed tickets | #2487  
| Doc PR        | na
To test:
```
./bin/pm2 start -c '* * * * *' --no-autorestart --no-daemon test/fixtures/cron_no_autorestart.js
```
Wait at least 1 min
=> Allow to use cron with autorestart=false scripts

examples/sourcemap-auto-resolve/API.js, lib/API.js, lib/API/Version.js, test/programmatic/json_validation.mocha.js, test/programmatic/max_memory_limit.js
Just deleted double semi in a few files.
=> Deleted double semi

lib/API/CliUx.js
=> fix: #4021 removed version column from stacked table body

bin/pm2, lib/API.js, lib/API/Extra.js, lib/API/Serve.js, test/e2e/cli/serve.sh, test/fixtures/serve/ecosystem-serve.json, test/fixtures/serve/other.html
| Fixed tickets | #4210, #3081
=> PM2 Serve v2

lib/API/Serve.js
=> Fix pm2 serve urlencode 404 situation

package.json
This resolves the axios vulnerability https://www.npmjs.com/advisories/880
=> mro: upgrade js-api

CHANGELOG.md, lib/API/CliUx.js, lib/API/pm2-plus/auth-strategies/CliAuth.js, lib/API/pm2-plus/auth-strategies/WebAuth.js
=> Fix typos (environement -> environment)

lib/API/schema.json, lib/Common.js, lib/tools/passwd.js
| Fixed tickets | #4058, #4262
=> Fix: Allow usernames in uid/gid/user again (fixes #4058, #4262)

lib/API/LogManagement.js
=> fix: only add each process name to regexList once

lib/API.js, lib/API/Serve.js
=> Added HOST enviroment

README.md, lib/API.js, lib/API/CliUx.js, lib/API/Dashboard.js, lib/API/schema.json, lib/Client.js, lib/binaries/CLI.js
=> Add process namespaces feature #3471

CHANGELOG.md, lib/API/Modules/Modularizer.js, package.json
https://github.com/toufik-airane fixed the vulnerability associated with Command Injection.
This fix is being submitted on behalf of https://github.com/toufik-airane - they have been awarded $25 for fixing the vulnerability through the huntr bug bounty program.
Think you could fix a vulnerability like this - get involved (https://huntr.dev).
Q | A
Version Affected | ALL
Bug Fix | YES
Further References | https://github.com/418sec/pm2/pull/2
=> pm2 - Command Injection - Fix:

lib/API/Modules/Modularizer.js
=> fix for huntr

lib/Common.js, test/e2e.sh, test/e2e/logs/log-create-not-exist-dir.sh, test/fixtures/log-create-not-exist-dir/echo.js
| Fixed tickets | #4844
| Doc PR        | no need
=> Fix/creating log folder in sync mode.

lib/API/Modules/NPM.js
=> fix(npm): Typo in "deleteing"

lib/ProcessContainer.js
=> Operation not permitted on call setgid, fix: #2957

lib/VersionCheck.js
=> fix: remove constants import from VersionCheck (not needed)

packager/setup.deb.sh
| Tests pass?   | 
Using lts https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions makes sure this won't need to be updated again !
=> update node version in setup.deb.sh by using lts

paths.js
overide -> override
| Bug fix?      |no
=> refactor: fix typo in paths.js

lib/API/UX/pm2-ls.js
If id of a process is > 999, this is how the `pm2 list` table currently looks like:
This PR fixes the bug.
1/ Added `list.forEach((l) => (l.pm2_env.pm_id %= 10));` on top of the function:
2/ Added `list.forEach((l) => (l.pm2_env.pm_id += 10))`
3/ Added `list.forEach((l) => (l.pm2_env.pm_id += 100));`
4/ Added `list.forEach((l) => (l.pm2_env.pm_id += 1000));`
5/ Added `list.forEach((l) => (l.pm2_env.pm_id += 10000));`
6/ Added `list.forEach((l) => (l.pm2_env.pm_id += 100000));`
Conclusion: it works.
=> fix large id erasure in "pm2 list"

types/index.d.ts
=> Add pm2.sendDataToProcessId(packet) signature
